### ISSUE TITLE
Cannot serialize a bytes object larger than 4 GiB

### ISSUE THREAD

**Issue by tly627** [cabooster/DeepCAD-RT#1]
Hi, thanks for providing us this nice algorithm! I have configured the environment according to the instructions but I ran into an issue when I train the model. Whatever parameters I use, there will be an error saying "Cannot serialize a bytes object larger than 4 GiB". How can I solve this problem? FYI, I am using Windows 10 with NVIDIA GeForce RTX 3070.

**Comment by cabooster** [comment]
Hi, I never encountered this error before. Could you please provide more information, especially which line this error originated from? This is helpful for debugging.

**Comment by tly627** [comment]
Thanks for the quick response. Here is the error:

(deepcad) C:\Users\Tin\DeepCAD-RT>python script.py train
←[1;31mTraining parameters -----> ←[0m
Namespace(GPU='0', b1=0.5, b2=0.999, batch_size=1, datasets_folder='DataForPytorch', datasets_path='datasets', fmap=16, gap_h=75, gap_s=75, gap_w=75, img_h=150, img_s=150, img_w=150, lr=5e-05, n_epochs=30, ngpu=1, normalize_factor=1, output_dir='./results', pth_path='pth', select_img_num=100000, train_datasets_size=3500)
←[1;31mImage list for training -----> ←[0m
Total number ----->  1
550Vx575H_FOV_30Hz_0.3power_00001_low_MCorr.tif
←[1;31mUsing 1 GPU for training -----> ←[0m
Traceback (most recent call last):
  File "train.py", line 96, in <module>
    for iteration, (input, target) in enumerate(trainloader):
  File "C:\Users\Tin\anaconda3\envs\deepcad\lib\site-packages\torch\utils\data\dataloader.py", line 355, in __iter__
    return self._get_iterator()
  File "C:\Users\Tin\anaconda3\envs\deepcad\lib\site-packages\torch\utils\data\dataloader.py", line 301, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Tin\anaconda3\envs\deepcad\lib\site-packages\torch\utils\data\dataloader.py", line 914, in __init__
    w.start()
  File "C:\Users\Tin\anaconda3\envs\deepcad\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\Tin\anaconda3\envs\deepcad\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Tin\anaconda3\envs\deepcad\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Tin\anaconda3\envs\deepcad\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Tin\anaconda3\envs\deepcad\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
OverflowError: cannot serialize a bytes object larger than 4 GiB

**Comment by cabooster** [comment]
This problem may be caused by the poor multiprocessing support of your environment or device. I think you can solve this problem in two possible ways:
1. Jump to the source code (C:\Users\Tin\anaconda3\envs\deepcad\lib\multiprocessing\reduction.py) and change this line `def dump(obj, file, protocol=None):` into `def dump(obj, file, protocol=4):`
2. Reduce the size of the training stack to <4GB by removing some frames.

**Comment by cabooster** [comment]
I am sorry that I reply you late. The reason for this error is that you use the Windows system to run our script, and the `num_worker` should be set to 0. Good news! We update the DeepCAD-RT version, and this parameter is easy to edit.
