### ISSUE TITLE
Error when completing Epoch in demo_train pipeline

### ISSUE THREAD

**Issue by claudioez** [cabooster/DeepCAD-RT#28]
Hi,

when completing the first epoch in the demo_train_pipeline.py I  get the following error:

any clues what can cause this problem?

Thanks in advance, Claudio.

Traceback (most recent call last):
  File "demo_train_pipeline.py", line 77, in <module>
    tc.run()
  File "C:\ProgramData\anaconda3\envs\deepcadrt2\lib\site-packages\deepcad\train_collection.py", line 85, in run
    self.train()
  File "C:\ProgramData\anaconda3\envs\deepcadrt2\lib\site-packages\deepcad\train_collection.py", line 328, in train
    self.save_model(epoch, iteration)
  File "C:\ProgramData\anaconda3\envs\deepcadrt2\lib\site-packages\deepcad\train_collection.py", line 367, in save_model
    torch.onnx.export(self.local_model.module, input, onnx_save_name, export_params=True,input_names=input_name, output_names=output_name,opset_version=11, verbose=False)
  File "C:\ProgramData\anaconda3\envs\deepcadrt2\lib\site-packages\torch\onnx\utils.py", line 506, in export
    _export(
  File "C:\ProgramData\anaconda3\envs\deepcadrt2\lib\site-packages\torch\onnx\utils.py", line 1620, in _export
    proto = onnx_proto_utils._add_onnxscript_fn(
  File "C:\ProgramData\anaconda3\envs\deepcadrt2\lib\site-packages\torch\onnx\_internal\onnx_proto_utils.py", line 228, in _add_onnxscript_fn
    model_proto = onnx.load_from_string(model_bytes)
AttributeError: module 'onnx' has no attribute 'load_from_string'

**Comment by cabooster** [comment]
First, make sure you have followed the steps in our README for environment installation. Then, check if your version of the onnx Python package is 1.9.0. This error could also be related to your Python version being 3.9. You can try creating a new environment or, if you don't need the MATLAB version of DeepcadRT, you can choose to comment out the line 'torch.onnx.export(self.local_model.module, input, onnx_save_name, export_params=True, input_names=input_name, output_names=output_name, opset_version=11, verbose=False)' in the train_collection.py file. This line does not affect other processes.

**Comment by claudioez** [comment]
"First, make sure you have followed the steps in our README for environment installation." 
Sadly these steps did not result in a successful installation. Therefore I am using a newer python version than the suggested one.
Anyway, removing the torch.onnx... line did the trick! 

Thanks a lot, CLaudio.
